In [1]:
# Import required libraries
import requests
import json
import pandas as pd

# API URL
url = 'https://api.tickertape.in/screener/query'

# API Payload
payload = {
    "sortBy": "mrktCapf",
    # limit data within range
    "match": {"mrktCapf": {"g": 0, "l": 990301.9231}},
    "sortOrder": -1,
    # add various other parameters according to you need
    "project": ["subindustry", "mrktCapf", "lastPrice", "apef"],
    "offset": 0,
    "count": 500,  # number of Stocks
    "sids": []
}

# API headers
headers = {
    'user-agent':
    'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Mobile Safari/537.36',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
}

# Make API request and store response as JSON
r = requests.post(url=url, json=payload, headers=headers).json()

# Initialize lists to store data
Ticker_ls, Name_ls, Last_Price_ls, Market_Cap_ls, Sector_ls = [], [], [], [], []

# Iterate over the response data and extract required information
for result in r['data']['results']:
    name = result[u'stock'][u'info'][u'name']
    ticker = result[u'stock'][u'info'][u'ticker']
    sector = result[u'stock'][u'info'][u'sector']
    # this is of type str and not type float
    lastprice = "%.2f" % result[u'stock'][u'advancedRatios'][u'lastPrice']
    # this is of type str and not type float
    marketcap = "%.2f" % result[u'stock'][u'advancedRatios'][u'mrktCapf']
    Name_ls.append(name)
    Ticker_ls.append(ticker)
    Sector_ls.append(sector)
    Last_Price_ls.append(lastprice)
    Market_Cap_ls.append(marketcap)

# Create a dataframe from the extracted data
df = pd.DataFrame([Name_ls, Ticker_ls, Sector_ls,
                  Market_Cap_ls, Last_Price_ls]).T
df.columns = ["Name", "Ticker", "Sector", "Market Cap", "Last Price"]

# Decorate the dataframe with left-aligned text
df = df.style.set_properties(**{'text-align': 'left'})
df = df.set_table_styles(
    [dict(selector='th', props=[('text-align', 'left')])])

# Display the dataframe
display(df